'use strict';

const fs   = require('fs');
const path = require('path');
const https = require('https');

const root     = __dirname;
const srcDir   = path.join(root, 'src');
const audioDir = path.join(srcDir, 'audio');
const distDir  = path.join(root, 'dist');

// ── SAMPLE LIST ────────────────────────────────────────────────
// Filenames as they exist on the CDN.  "Ds" = D-sharp, "Fs" = F-sharp.
// Tone.Sampler interpolates all other notes from these 26.
const SAMPLE_FILES = [
  'A0','C1','Ds1','Fs1','A1','C2','Ds2','Fs2',
  'A2','C3','Ds3','Fs3','A3','C4','Ds4','Fs4',
  'A4','C5','Ds5','Fs5','A5','C6','Ds6','Fs6',
  'A7','C8',
];

const SAMPLE_BASE_URL = 'https://tonejs.github.io/audio/salamander/';

// ── SOURCE FILE LISTS ──────────────────────────────────────────
const CSS_FILES = [
  'css/variables.css', 'css/reset.css',      'css/typography.css',
  'css/components.css','css/layout.css',      'css/screens.css',
  'css/animations.css',
];

const JS_FILES = [
  'data/intervals.js', 'data/chords.js',   'data/cadences.js', 'data/levels.js',
  'js/storage.js',     'js/audio.js',       'js/scoring.js',    'js/questions.js',
  'js/charts.js',      'js/ui.js',          'js/app.js',
];

// ── HELPERS ────────────────────────────────────────────────────
function downloadFile(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'auris-build/1.0' } }, (res) => {
      // Follow redirects
      if (res.statusCode === 301 || res.statusCode === 302) {
        return downloadFile(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`HTTP ${res.statusCode} — ${url}`));
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', reject);
    }).on('error', reject);
  });
}

// "Ds1" → "D#1",  "Fs4" → "F#4",  "A4" → "A4"
function filenameToPitchKey(name) {
  return name.replace('Ds', 'D#').replace('Fs', 'F#');
}

// ── STEPS ──────────────────────────────────────────────────────

async function step1_downloadSamples() {
  console.log('\n[1/3] Piano samples');
  if (!fs.existsSync(audioDir)) fs.mkdirSync(audioDir, { recursive: true });

  let downloaded = 0;
  let cached     = 0;

  for (const note of SAMPLE_FILES) {
    const filename  = `${note}.mp3`;
    const localPath = path.join(audioDir, filename);
    const exists    = fs.existsSync(localPath) && fs.statSync(localPath).size > 1024;

    if (exists) {
      cached++;
      continue;
    }

    process.stdout.write(`  ↓ ${filename.padEnd(10)}`);
    const data = await downloadFile(`${SAMPLE_BASE_URL}${filename}`);
    fs.writeFileSync(localPath, data);
    downloaded++;
    console.log(`${(data.length / 1024).toFixed(0)} KB`);
  }

  const totalKB = SAMPLE_FILES.reduce((s, n) => {
    return s + fs.statSync(path.join(audioDir, `${n}.mp3`)).size;
  }, 0) / 1024;

  if (cached)     console.log(`  ${cached} files already cached`);
  if (downloaded) console.log(`  ${downloaded} files downloaded`);
  console.log(`  Total raw audio: ${totalKB.toFixed(0)} KB across ${SAMPLE_FILES.length} files`);
}

function step2_buildEmbeddedSamplesJS() {
  console.log('\n[2/3] Encoding samples to Base64');
  const entries = SAMPLE_FILES.map(note => {
    const buf  = fs.readFileSync(path.join(audioDir, `${note}.mp3`));
    const key  = filenameToPitchKey(note);
    const b64  = buf.toString('base64');
    process.stdout.write('.');
    return `  "${key}": "data:audio/mp3;base64,${b64}"`;
  });
  console.log(' done');

  const js = `/* === Embedded Salamander Piano Samples (Base64) ===\n`
           + `   Generated by build.js — do not edit manually\n`
           + `   Source: ${SAMPLE_BASE_URL} */\n`
           + `const EMBEDDED_SAMPLES = {\n${entries.join(',\n')}\n};\n`;

  console.log(`  Embedded object: ${(js.length / 1024).toFixed(0)} KB`);
  return js;
}

async function step3_assemble(samplesJS) {
  const version = require(path.join(root, 'package.json')).version;
  const outName = `auris-v${version}.html`;
  console.log(`\n[3/3] Assembling dist/${outName}`);

  const css = CSS_FILES.map(f =>
    `/* === ${f} === */\n${fs.readFileSync(path.join(srcDir, f), 'utf8')}`
  ).join('\n\n');

  const js = JS_FILES.map(f =>
    `/* === ${f} === */\n${fs.readFileSync(path.join(srcDir, f), 'utf8')}`
  ).join('\n\n');

  // EMBEDDED_SAMPLES is prepended before all other JS so every module can reference it
  const fullJS = samplesJS + '\n' + js;

  let html = fs.readFileSync(path.join(srcDir, 'index.html'), 'utf8');
  html = html.replace('{{CSS}}', css);
  html = html.replace('{{JS}}',  fullJS);

  if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });

  // Write versioned file and keep auris.html as a stable alias
  const outPath     = path.join(distDir, outName);
  const aliasPath   = path.join(distDir, 'auris.html');
  fs.writeFileSync(outPath,   html, 'utf8');
  fs.writeFileSync(aliasPath, html, 'utf8');

  const sizeMB = (fs.statSync(outPath).size / (1024 * 1024)).toFixed(2);
  console.log(`  Output: dist/${outName} — ${sizeMB} MB`);
  console.log(`  Alias:  dist/auris.html`);
  return { sizeMB, outName };
}

// ── MAIN ───────────────────────────────────────────────────────
async function build() {
  console.log('Auris Build\n===========');

  await step1_downloadSamples();
  const samplesJS          = step2_buildEmbeddedSamplesJS();
  const { sizeMB, outName } = await step3_assemble(samplesJS);

  console.log(`\n✓ Build complete — dist/${outName} (${sizeMB} MB)`);
  console.log('  dist/auris.html also updated (stable download alias).');
  console.log('  Open either file on any device — works fully offline.\n');
}

build().catch(err => {
  console.error('\n✗ Build failed:', err.message);
  process.exit(1);
});
